image: docker

stages:
  - build
  - test

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
  - master

test:
  stage: test
  script:
    - docker run -d --name sdk-testing-mock registry.gitlab.com/apilayer/eversign/sdk-testing-mock
    - docker run -d --name eversign-php-sdk --link sdk-testing-mock:sdk-testing-mock $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - sleep 5

    - docker exec sdk-testing-mock ./send_command set_test_case create_document_from_template
    - docker exec eversign-php-sdk sh -c 'SDK_TESTING_MOCK_URL="http://sdk-testing-mock:8888/api/" vendor/bin/phpunit sdk/Eversign/Test/CreateDocumentFromTemplateTest.php'

    - docker exec sdk-testing-mock ./send_command get_test_results

after_script:
  - docker rm -f sdk-testing-mock || return 0
  - docker rm -f eversign-php-sdk || return 0
